name: projet_kosmos
description: "Projet test pour l'entreprise kosmos"

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  firebase_storage: ^12.0.1
  image_picker: ^1.1.2
  firebase_app_check: ^0.3.0+1
  another_flushbar: ^1.12.30
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: SofiaPro
      fonts:
        - asset: lib/assets/fonts/Sofia_Pro_Regular_Az.otf
