// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCySXxpdHfgN7JjaZghhvzo1PIlS1UaZPU',
    appId: '1:513653676733:web:9bbfae7bf5a76549ea75d4',
    messagingSenderId: '513653676733',
    projectId: 'kosmos-fd37a',
    authDomain: 'kosmos-fd37a.firebaseapp.com',
    storageBucket: 'kosmos-fd37a.appspot.com',
    measurementId: 'G-RZ16EM29L8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJnLQnoFN7Y5B9Vn0xHEoAW6oxt0WWA0k',
    appId: '1:513653676733:android:a44f1f2dc8f6c543ea75d4',
    messagingSenderId: '513653676733',
    projectId: 'kosmos-fd37a',
    storageBucket: 'kosmos-fd37a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBunsJHdTwfvoepIr_ZkQTpbnaleQvQDeY',
    appId: '1:513653676733:ios:0f6ce77b6023dbccea75d4',
    messagingSenderId: '513653676733',
    projectId: 'kosmos-fd37a',
    storageBucket: 'kosmos-fd37a.appspot.com',
    iosClientId: '513653676733-cj77pf4dub72om14lqaeup44d8l050gv.apps.googleusercontent.com',
    iosBundleId: 'fr.avramov.projetKosmos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBunsJHdTwfvoepIr_ZkQTpbnaleQvQDeY',
    appId: '1:513653676733:ios:0f6ce77b6023dbccea75d4',
    messagingSenderId: '513653676733',
    projectId: 'kosmos-fd37a',
    storageBucket: 'kosmos-fd37a.appspot.com',
    iosClientId: '513653676733-cj77pf4dub72om14lqaeup44d8l050gv.apps.googleusercontent.com',
    iosBundleId: 'fr.avramov.projetKosmos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCySXxpdHfgN7JjaZghhvzo1PIlS1UaZPU',
    appId: '1:513653676733:web:d243e3cda2b4852fea75d4',
    messagingSenderId: '513653676733',
    projectId: 'kosmos-fd37a',
    authDomain: 'kosmos-fd37a.firebaseapp.com',
    storageBucket: 'kosmos-fd37a.appspot.com',
    measurementId: 'G-D57JFL6HT1',
  );

}